In [14]:
# Dependencies
import matplotlib.pyplot as plt
import requests
import pandas as pd
import numpy as np
import gmaps
import json

from config import g_key

In [15]:
# Read our city file from WeatherPy
city_weather_data = pd.read_csv("city_weather_data.csv", index_col=0)
city_weather_data

,city,Longitude,Latitude,Max Temp,Humidity,Clouds,Wind Speed,Country,Date Time
0,cabo san lucas,-109.91,22.89,96.80,42,40,13.87,MX,1594071431
1,hokitika,170.97,-42.72,47.95,84,67,4.70,NZ,1594071613
2,leningradskiy,178.42,69.38,46.74,77,97,5.91,RU,1594071613
3,airai,125.41,-8.93,57.18,100,33,4.21,TL,1594071613
4,codrington,141.97,-38.27,47.26,83,60,1.43,AU,1594071613
...,...,...,...,...,...,...,...,...,...
522,kerema,145.78,-7.96,76.66,87,21,2.35,PG,1594071649
523,lasa,10.70,46.62,59.00,58,40,10.29,IT,1594071649
524,maceio,-35.74,-9.67,75.20,78,20,3.36,BR,1594071573
525,antalaha,50.28,-14.90,71.13,91,99,11.30,MG,1594071649
526,amga,131.96,60.90,61.77,60,38,1.61,RU,1594071649

In [31]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

# Get the city Latitudes and Longitudes values
points = city_weather_data[["Latitude", "Longitude"]]

# Get the humidity values
humidities = city_weather_data["Humidity"]

# Create a Humidity Heatmap layer
fig = gmaps.figure(center=(55.0, -10.0), zoom_level=2)

heat_layer = gmaps.heatmap_layer(points, weights=humidities, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 3)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [36]:
# Find cities with my ideal weather conditions

ideal_cities = city_weather_data.loc[(city_weather_data["Humidity"] < 60) & (city_weather_data["Max Temp"] > 74) & (city_weather_data["Max Temp"] < 81) & (city_weather_data["Wind Speed"] <= 10) & (city_weather_data["Clouds"] < 10)].dropna()
ideal_cities

,city,Longitude,Latitude,Max Temp,Humidity,Clouds,Wind Speed,Country,Date Time
16,korla,86.15,41.76,75.52,23,0,4.65,CN,1594071614
70,jaciara,-54.97,-15.97,78.30,43,0,3.65,BR,1594071617
100,gravelbourg,-106.55,49.88,78.24,29,9,3.85,CA,1594071619
105,requena,-1.10,39.49,75.99,42,0,3.22,ES,1594071619
144,zatoka,30.47,46.07,78.80,54,3,8.95,UA,1594071622
215,wana,69.57,32.30,77.90,44,4,1.50,PK,1594071627
323,swift current,-107.80,50.28,77.00,41,1,9.17,CA,1594071635
471,chapais,-74.85,49.78,80.60,24,1,5.82,CA,1594071645
485,zhob,69.45,31.34,77.43,43,0,2.73,PK,1594071646

In [37]:
# Add a column for nearest hotel

ideal_cities["Nearest Hotel"] = ""

ideal_cities

,city,Longitude,Latitude,Max Temp,Humidity,Clouds,Wind Speed,Country,Date Time,Nearest Hotel
16,korla,86.15,41.76,75.52,23,0,4.65,CN,1594071614,
70,jaciara,-54.97,-15.97,78.30,43,0,3.65,BR,1594071617,
100,gravelbourg,-106.55,49.88,78.24,29,9,3.85,CA,1594071619,
105,requena,-1.10,39.49,75.99,42,0,3.22,ES,1594071619,
144,zatoka,30.47,46.07,78.80,54,3,8.95,UA,1594071622,
215,wana,69.57,32.30,77.90,44,4,1.50,PK,1594071627,
323,swift current,-107.80,50.28,77.00,41,1,9.17,CA,1594071635,
471,chapais,-74.85,49.78,80.60,24,1,5.82,CA,1594071645,
485,zhob,69.45,31.34,77.43,43,0,2.73,PK,1594071646,

In [42]:
# create a params dict that will be updated with new city each iteration
params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

# Loop through the cities_pd and run a lat/long search for each city
for index, row in ideal_cities.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    lat = row["Latitude"]
    lng = row["Longitude"]
    city_name = row["city"]

    # update address key value
    params['location'] = f"{lat},{lng}"

    # make request
    response = requests.get(base_url, params=params)
    
    # print the response url, avoid doing for public github repos in order to avoid exposing key
    #print(response.url)
    
    # convert to json
    response = response.json()
    #print(json.dumps(response, indent=4, sort_keys=True))
    
    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        ideal_cities.loc[index, "Hotel Name"] = response["results"][0]["name"]

    except (KeyError, IndexError):
        print(f"No hotel within 5000 meters of {city_name} city/.... skipping.")

#     cities_pd.loc[index, "Lat"] = cities_lat_lng["results"][0]["geometry"]["location"]["lat"]
#     cities_pd.loc[index, "Lng"] = cities_lat_lng["results"][0]["geometry"]["location"]["lng"]

# Visualize to confirm hotels appear
ideal_cities

No hotel within 5000 meters of wana city/.... skipping.

,city,Longitude,Latitude,Max Temp,Humidity,Clouds,Wind Speed,Country,Date Time,Nearest Hotel,Hotel Name
16,korla,86.15,41.76,75.52,23,0,4.65,CN,1594071614,,Kangcheng Jian Guo International Hotel
70,jaciara,-54.97,-15.97,78.30,43,0,3.65,BR,1594071617,,Hotel Toquinho
100,gravelbourg,-106.55,49.88,78.24,29,9,3.85,CA,1594071619,,Heritage Place B&B
105,requena,-1.10,39.49,75.99,42,0,3.22,ES,1594071619,,Hotel DoÃ±a Anita
144,zatoka,30.47,46.07,78.80,54,3,8.95,UA,1594071622,,Bless Resort & Villa
215,wana,69.57,32.30,77.90,44,4,1.50,PK,1594071627,,NaN
323,swift current,-107.80,50.28,77.00,41,1,9.17,CA,1594071635,,Holiday Inn Express & Suites Swift Current
471,chapais,-74.85,49.78,80.60,24,1,5.82,CA,1594071645,,HÃ´tel OpÃ©miska
485,zhob,69.45,31.34,77.43,43,0,2.73,PK,1594071646,,Rohail hotel Zhob

In [46]:
# set up for hotel markers
marker_detail = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{city}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
hotel_marker = [marker_detail.format(**row) for index, row in ideal_cities.iterrows()]
locations = ideal_cities[["Latitude","Longitude"]]

In [47]:
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations, info_box_content = hotel_marker)

# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))